language: cpp
sudo: yes
dist: trusty

addons:
  apt:
    packages:
      - libjemalloc-dev

script:
  # Build and run unit tests
  - |
      set -ex -o pipefail
      # use the Dockerfile to build the glnexus_tests container
      effective_build_type=$TRAVIS_BUILD_TYPE
      if [ "$effective_build_type" == "Valgrind" ]; then
        effective_build_type="Release"
      fi
      cat Dockerfile | docker build --no-cache -t glnexus_tests --build-arg git_revision=$TRAVIS_COMMIT --build-arg build_type=$effective_build_type -
      # copy the /GLnexus folder out of the image to mount for subsequent use
      docker run --rm -v /:/io glnexus_tests cp -r /GLnexus/ /io
      # Run the tests
      if [ "$TRAVIS_BUILD_TYPE" == "Valgrind" ]; then
        docker run --rm -e ROCKSDB_VALGRIND_RUN=1 -v /GLnexus:/GLnexus glnexus_tests bash -ex -o pipefail -c "valgrind --soname-synonyms=somalloc=*jemalloc* --suppressions=test/GLnexus.supp --leak-check=full --gen-suppressions=all --error-exitcode=1 ./unit_tests -d yes"
      else
        docker run --rm -v /GLnexus:/GLnexus glnexus_tests
        sudo chown -R $USER /GLnexus
        if [ "$TRAVIS_BUILD_TYPE" == "Coverage" ]; then
          sudo pip install -U cpp-coveralls
          pushd /GLnexus && coveralls --include src --include include --gcov-options '\-lp' && popd
        else
          /GLnexus/glnexus_cli -h
          /GLnexus/test/jemalloc_linking.sh
        fi
      fi
      # launch medium tests from the medium-tests branch only
      if [ "$TRAVIS_BRANCH" == "medium-tests" ] && [ "$TRAVIS_BUILD_TYPE" == "Release" ]; then bash test/launch_medium_tests.sh; fi

env:
  global:
    # Encrypted Github credential (using yifei's account)
    - secure: "i/0Zm5ZtBe8oHaRHGBmlXzcaS61VoovEz758LY4GFKl0PncwFfFWAN8Yt2iWBZPLu5hHXudHKNaJc5ORqoqggLYzgDue++6mqL5lQfJbl9Luh/itoi20M9pt+I2dMW+9qLipROH3tTxGSiIVxacRcAbkxMdHz71iiHZ0PViLQ0UyE12ugSqNn81VYUDzgPISc0vs+8I76FGXB7i4Ox1HO2d8OLJwfnzriBXuQyHbLJT4fA1yz53sT+RNc5iTR4/xGA5qfnuGgrjcLZYsjh8bSzjvsYeA3RddIcsjmOhCw/ZvEMIvvqi9oAV//EiO95c8l+GG3U0k/78u7YafROnr901aDXSkS+1KitOT3n9KoQkuDZMpqUGCX30tSBefpnpq8EdxibaUfauhrkf0mNbZepZU18vIGB3h49lGGkBkJ1tR5fw/htnm7hUywXVRkcur/DYqPtsc3aM0HViEGsMplTIEsCYJE/O39Lde1ksJrYQCYp4AAlgmSsrKo0WLydc8gnbfYhxws+NzI2VH5mkr7BCEiK6fG2CIOT0xFJqCQbkhFOKVKyArUBou8bKTAbB7CFZNeMcbUEuVWY5NJ0Gvn4uiYOa47e/P+i8FO/LV+Rcpx8Jabn0E5bL1gRHuMqo7RfdF9B7ape6w2+Qyn2MFkplSfjadVP8mFefMIckYjU4="
    # GLNEXUS_TEST_PROJECT_ID
    - secure: "J8yut92zrAcKFAcYFCLUzcYzEalFU+LkTCoMyK1fFt4k+RSM0LwdqvOz1n/SQHHBHW0OiJ2qQ68N8bcvyN7ggaHDfSxZGjBC9/WX1HrUZ7kp2exS/R1iHv20j6gXuy0FHuOGZiEyVq2rjUgtyWqIpwE/nuCLo4P1tqyKSng2ff4Jay41Bjt5FE8BNSLGr1y6I1VjV5lkVb86gbcfKPiaWuvObbTwF4I/pp/d3fjSzvMiZ7P/cT3C2ROpC9NK7UDRgo+qBj057aLyTEuPle0G6LpfnV9eHB+ddGxuXtMyrbDbLR2SCyvOWqlyyWzpzUEafb3v+qL+Oby6JFw/IEPv/Y/Gv8Rz8xEq6Vm1Do58t3kqvi2Puz/cRrZI9IWBuNVJuBJGiAb+BenIMuCdMNAFxMFxO/ENanYRDU3Bo6ZYa4Rin9ROYRyqYsYEU9zRx/Ni/8E2M4MbDXeoPQTx72h+yetzo7IAMIdQOovrLKtUH6+IKitjJKs41oN64syBceNXm3bPEq3FQn1aSMd14kqwUSch0OnMVBzfEE8JXrrOihNzvrPVRHijd4bOYwHtr+vo002xUGwpACaXucQZfSeOYwFJjopG2+1pKuByk4/vItHI3ulArfzxmMLgkmqT9n0Dz0NkCS3NegmBmKd6CsqqWgl6iw9ivvtfWTo88K+ablY="
    # DX_AUTH_TOKEN (mlin)
    - secure: "oRCQp7xzW0o3NteAezjgByyChji3oPgPT2ChCSe3trDH2Ebuyo6/rTuT8g0OnyJ+1RGJrdGykJHMJw3k5RxhOpHG6EaZOHY3gKr8pYyf5Jvs7sLFT3e2Td3xAvNig2e4UJ8P0GnXu1VBUUpTt4IctVknGIHhM2kt9QJ7uKZjgEnU/wUpF+JpJFHJQc6PHiDpicjhpYZhrNBtLE2RH0OLL3hvRweVeKsttVbhV5i6arX8d60e9JHbKTmh1QC1WTDfzzcpFGutruztOAZRJ+PUl1eIp82EfbeVatDw2xwN7BMNHjFK5SYD1SwZz/cD0KDlFcPdUk5CJgLKJcLcmjh6baisg4+HpOZHv5hFEk7KdtoWsmoNUqeFJ9PoWT15vwy629bxRYBsFXEDVJ+08siRibos/H9fLs1oW+9rWnmA/cZc9AAjfTtg6IPy2Xtamj1feCKo3qO5gBIa+gQNn2F9wmx4TJ8hPAQDqBw/Ypwz9RMx/8wo4Dq2y+JcWHeOxMNjIi/bHRGhzohaUys/cN4YrTjpPFMnZeK4uCfrKaw020tB+D2JASVyAKx1xPlqAZKbjW7X5p/zxQOfVdVDEVCVQOKS6XInleS5k9qALB1/u7ab3XDc5+A8Y+jaNXlOIoWCqZ73SvFrO8MS6KKCCVgp309BDm0BJ7ssZeahan3ai2E="

matrix:
  include:
    - env: TRAVIS_BUILD_TYPE=Debug
    - env: TRAVIS_BUILD_TYPE=Coverage
    - env: TRAVIS_BUILD_TYPE=Valgrind
    - env: TRAVIS_BUILD_TYPE=Release
    # NB: some warnings we set to errors are detected only in Release mode (with
    # compiler optimizations on). http://stackoverflow.com/q/11061970

deploy:
  provider: releases
  api_key:
    secure: OXrWL2sImjEpPDpFnKhhdpccklYauXAGtErJHjVMc8VJtjsHt4xhsIpPUytdnOH0sbdno8PLEy0Tb3C4Ff5Xq82WU7B5TrYdRzEvq14i/Y+eiqDOUfI7ttvCJwQHjvD01/B/1qFLV9Mz1lR/dkR7NXr+e7GNEStjq1OeiyXYb6WSkFomW73yiNb084h/6wetRGx/o3Jnrcs56vBQyq3GpQc18GpDiBskZoEf9Z1SJXwfcRXKTsUJC6M95ZaRktBS09eVrr0c9zRW4meg4+Hb5dQlNItD8TUSt4Qz5Ilyzwvo7TpWtAKatVgU0xd8K+EDuFebwUOP3HbAje8m3kIbppkqvved5tfDEjw3vOaCUimoYCx2W6JXlhxct42VbesBexnZt0zLvxhR4bGv3p0Dckf1XgL2cK+IUie1VNcewHMCUGlwQBLDdcr2i8SLmWvYyyrp/k1d2KailmLCnwQbl3/eAtyGOEQtEamt3Fshd8Qs9806tw9ZfgKjNex3ELTEFHCWAatcsgANcP6QZfxl6kqKVTIbid0WjhW6270bAs5+Bu/bo8Tx2xWoWwZNXllyYg2fxVurcdyZQ5DCmyyMQIA5+fWq8RIbmkqpV+LhDHZKgeKimwzKYb2rLr6IYLXTh99LuotLGojQSXnq/qGukYuFjC4azAjaP3ca63wNwUU=
  file: /GLnexus/glnexus_cli
  skip_cleanup: true
  on:
    repo: dnanexus-rnd/GLnexus
    tags: true
    condition: "$TRAVIS_BUILD_TYPE == Release"
